# Generated by Django 5.0.6 on 2024-06-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_date_event_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_time',
        ),
        migrations.AddField(
            model_name='event',
            name='date_and_time',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
